services:
  - type: web
    name: universal-downloader-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && mkdir -p bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp && chmod a+rx bin/yt-dlp
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PATH
        value: /opt/render/project/src/bin:$PATH
