services:
  - type: web
    name: universal-downloader-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && apt-get update && apt-get install -y python3 python3-pip && pip3 install -U yt-dlp
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
