services:
  - type: web
    name: universal-downloader-backend
    env: node
    region: oregon
    plan: free
    buildCommand: bash build-render.sh
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PATH
        value: /opt/render/project/src/bin:$PATH
