services:
  - type: web
    name: universal-downloader-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp && chmod a+rx ./yt-dlp
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PATH
        value: /opt/render/project/src:$PATH
